name: Hello world workflow
on:
  push:
    branches:
      - main
    paths:
      - 'to_check/**'

  # pull_request:
  #   branches:
  #     - main
  # workflow_dispatch:

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: fasihburak 
# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: hello world
#         run: echo "Changes made"
#         shell: bash

