name: Hello world workflow
on:
  push:
    branches:
      - main
    paths:
      - 'to_check/**'
  pull_request:
    branches:
      - main
    paths:
      - 'to_check/**'
  workflow_dispatch: # Gives you a button to trigger the workflow manually.

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # You can utilize any third-party action in the market place or in a public repo.
      - name: hello world
        run: echo "Changes made"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Workflow completed"
        shell: bash
        